import {useCallback,useEffect,useRef,useState} from 'react';import {AlertCircle,Box,CheckCircle2,Clock,File,PauseCircle,RefreshCw,Terminal} from 'lucide-react';import {useNavigate,useParams} from 'react-router-dom';import {api} from '../api';import type {Job} from '../types';import {Button,PageHeader} from '../App';
const eventNames=['stage.log','stage.output','stage.started','stage.completed','job.status','job.completed','job.failed'];
export default function MonitorPage(){
 const {jobId=''}=useParams(),nav=useNavigate();const [job,setJob]=useState<Job>(),[connected,setConnected]=useState(false),logRef=useRef<HTMLDivElement>(null),redirected=useRef(false),loading=useRef(false);
 const load=useCallback(async()=>{if(loading.current)return;loading.current=true;try{const next=await api.job(jobId);setJob(next);if(next.status==='completed'&&!redirected.current){redirected.current=true;setTimeout(()=>nav(`/review/${next.projectId}`),1200)}}finally{loading.current=false}},[jobId,nav]);
 useEffect(()=>{redirected.current=false;void load();const es=new EventSource(`/api/jobs/${jobId}/events`);const refresh=()=>void load();es.onopen=()=>setConnected(true);es.onerror=()=>setConnected(false);eventNames.forEach(name=>es.addEventListener(name,refresh));const fallback=window.setInterval(refresh,3000);return()=>{eventNames.forEach(name=>es.removeEventListener(name,refresh));window.clearInterval(fallback);es.close()}},[jobId,load]);
 useEffect(()=>{if(logRef.current)logRef.current.scrollTop=logRef.current.scrollHeight},[job?.logs]);
 if(!job)return <div className="loading"><span/>正在连接任务…</div>;const passed=job.stages.filter(s=>s.status==='passed'||s.status==='skipped').length;
 return <><PageHeader eyebrow={`Attempt ${job.attempt} · ${connected?'实时连接':'轮询同步中'}`} title="任务执行监控" description={`实际后端：${job.actualBackend||'等待分配'} · 已通过 ${passed}/${job.stages.length} 个阶段`}/><div className="monitor-layout"><aside className="panel timeline"><h2>任务阶段</h2>{job.stages.map(s=><div className={`timeline-step ${s.status}`} key={s.id}>{s.status==='passed'?<CheckCircle2/>:s.status==='running'?<RefreshCw/>:s.status==='failed'?<AlertCircle/>:<Clock/>}<div><b>{s.label}</b><span>{s.status}</span></div><time>{s.duration||'--:--'}</time></div>)}<div className="passed-count">已通过 <b>{passed}</b> / {job.stages.length} 阶段</div></aside><section className="monitor-center"><div className="render-grid">{job.artifacts.filter(a=>a.type==='render').slice(-4).map(a=><figure key={a.id}><img src={a.url} alt={a.label}/><figcaption>{a.label}</figcaption></figure>)}{!job.artifacts.some(a=>a.type==='render')&&<div className="render-wait"><Box/><b>{job.currentStage?.replaceAll('_',' ')}</b><p>阶段产物将在通过后显示，页面关闭不会终止任务。</p></div>}</div></section><aside className="monitor-right"><div className="panel stage-card"><small>当前阶段</small><h2>{job.currentStage?.replaceAll('_',' ')||job.status}</h2><div className="pulse-line"><i/></div><span>资源队列：单 GPU 串行</span></div><div className="panel log-panel"><h2><Terminal/> 实时日志</h2><div ref={logRef}>{job.logs.map((l,i)=><p key={i}>{l}</p>)}</div></div><div className="panel artifacts"><h2>输出产物</h2>{job.artifacts.map(a=><a href={a.url} key={a.id} download><File/><span>{a.label}<small>{(a.byteSize/1048576).toFixed(2)} MB</small></span></a>)}</div></aside></div><div className="sticky-actions"><Button kind="secondary" onClick={()=>void load()}><RefreshCw/> 刷新快照</Button><span>{connected?'SSE 实时事件已连接':'SSE 断开时每 3 秒自动同步'}</span>{!['completed','failed','cancelled'].includes(job.status)&&<Button kind="danger" onClick={()=>api.cancel(job.id).then(setJob)}><PauseCircle/> 取消任务</Button>}{job.status==='failed'&&<Button onClick={()=>api.retry(job.id).then(j=>nav(`/jobs/${j.id}`))}>重试（新 Attempt）</Button>}</div></>
}
