import {useEffect,useState} from 'react';
import {CheckCircle2,Clock,Download,GitCompare,RefreshCw,ScrollText} from 'lucide-react';
import {useParams} from 'react-router-dom';
import {api} from '../api';
import type {RevisionRequest,Version} from '../types';
import ModelViewport from '../components/ModelViewport';
import {PageHeader} from '../App';

export default function RevisionMonitorPage(){
 const {revisionId=''}=useParams(),[job,setJob]=useState<RevisionRequest>(),[source,setSource]=useState<Version>(),[candidate,setCandidate]=useState<Version>(),[view,setView]=useState<'compare'|'logs'>('compare'),[error,setError]=useState(''),[reviewing,setReviewing]=useState(''),[lastUpdated,setLastUpdated]=useState('');
 const refresh=async()=>{const r=await api.revision(revisionId);setJob(r);setLastUpdated(new Date().toLocaleTimeString());const versions=await Promise.all([api.version(r.sourceVersionId),r.outputVersionId?api.version(r.outputVersionId):Promise.resolve(undefined)]);setSource(versions[0]);setCandidate(versions[1]);return r};
 useEffect(()=>{let alive=true,t:number;const poll=()=>refresh().then(r=>{if(alive&&['queued','processing'].includes(r.status))t=window.setTimeout(poll,1500)}).catch(e=>setError(e.message));poll();return()=>{alive=false;clearTimeout(t)}},[revisionId]);
 const review=async(cid:string,resultStatus:string)=>{setReviewing(cid);setError('');try{setJob(await api.reviewRevisionComment(revisionId,cid,resultStatus));setLastUpdated(new Date().toLocaleTimeString())}catch(e){setError(`复核提交失败：${(e as Error).message}`)}finally{setReviewing('')}};
 if(!job)return <div className="loading"><span/>正在读取修订任务…</div>;
 const reviewReady=job.status==='awaiting_review';
 return <><PageHeader eyebrow={`Reference Set v${job.referenceSet.number}`} title="候选重生成与逐条复核" description="并排检查源模型与候选模型，然后逐条提交 Comment 复核结果。" action={<button className="button secondary" onClick={()=>refresh().catch(e=>setError(e.message))}><RefreshCw/>刷新</button>}/><div className="revision-status-strip"><b className={reviewReady?'ready':''}>{job.status}</b><span>最后刷新：{lastUpdated||'--'}</span>{reviewReady&&<strong>候选版本已就绪，请开始逐条复核</strong>}</div><div className="revision-monitor"><aside className="panel"><h2><Clock/>任务与证据</h2><p>源版本：{source?`v${String(source.number).padStart(3,'0')}`:job.sourceVersionId}</p><p>候选版本：{candidate?`v${String(candidate.number).padStart(3,'0')}`:job.outputVersionId||'尚未生成'}</p><h3>Reference Set</h3>{job.referenceSet.assets.map(a=><a key={a.assetId} href={a.url} target="_blank"><Download/>{a.viewRole} · {a.name}</a>)}</aside><section className="panel revision-workspace"><div className="revision-tabs"><button className={view==='compare'?'active':''} onClick={()=>setView('compare')}><GitCompare/>模型对比</button><button className={view==='logs'?'active':''} onClick={()=>setView('logs')}><ScrollText/>执行日志</button></div>{view==='compare'?<div className="model-compare"><div><h3>源模型 · 保持不变</h3>{source?.model?<ModelViewport url={source.model.url} onStats={()=>{}} onSelect={()=>{}}/>:<div className="compare-empty">源模型不可用</div>}</div><div><h3>候选模型 · 待复核</h3>{candidate?.model?<ModelViewport url={candidate.model.url} onStats={()=>{}} onSelect={()=>{}}/>:<div className="compare-empty">{job.status==='processing'?'正在生成候选模型…':'候选模型不可用'}</div>}</div></div>:<div className="revision-logs">{job.logs.map((l,i)=><p key={i}>{l}</p>)}</div>}{job.errorSummary&&<div className="notice danger">{job.errorSummary}</div>}</section><aside className="panel review-panel"><h2>逐条 Comment 复核</h2>{!reviewReady&&<div className="notice">任务完成并进入 awaiting_review 后可提交复核。</div>}{job.comments.map(c=><article className="review-comment" key={c.id}><b>#{c.number} {c.title}</b><small>{c.status}</small><p>{c.description}</p>{reviewReady&&!c.resultStatus&&<div className="review-actions"><button disabled={reviewing===c.id} onClick={()=>review(c.id,'resolved')}>已解决</button><button disabled={reviewing===c.id} onClick={()=>review(c.id,'partially_resolved')}>部分解决</button><button disabled={reviewing===c.id} onClick={()=>review(c.id,'unresolved')}>未解决</button><button disabled={reviewing===c.id} onClick={()=>review(c.id,'new_issue')}>产生新问题</button></div>}{c.resultStatus&&<p className="review-result"><CheckCircle2/>{c.resultStatus}</p>}</article>)}{error&&<div className="notice danger">{error}</div>}</aside></div></>
}
