import {useEffect,useState} from 'react';import {Box,CheckCircle2,Eye,Wrench} from 'lucide-react';import {useNavigate,useParams} from 'react-router-dom';import {api} from '../api';import type {Version} from '../types';import ModelViewport from '../components/ModelViewport';import {PageHeader} from '../App';
export default function ReviewPage(){
 const {projectId=''}=useParams(),nav=useNavigate();const [versions,setVersions]=useState<Version[]>([]),[active,setActive]=useState<Version>(),[stats,setStats]=useState<Record<string,number|string>>({}),[selected,setSelected]=useState('未选择'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{api.versions(projectId).then(v=>{setVersions(v);setActive(v[0])}).catch(e=>setError(e.message))},[projectId]);
 const accept=async()=>{setBusy(true);try{await api.decide(active!.id,'accept','');setMessage('版本已确认并锁定');setActive(v=>v?{...v,status:'completed'}:v)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!active)return <div className="loading"><span/>正在读取版本…</div>;
 const q=active.qualityReport,isAccepted=active.status.startsWith('completed'),differences=q?.differences||[],reportStats=q?.stats||{};
 return <>{message&&<div className="accept-toast"><CheckCircle2/><div><b>{message}</b><span>后续精修将创建新版本，不覆盖当前版本。</span></div></div>}<PageHeader eyebrow={`项目 ${projectId.slice(0,8)} · 版本验收`} title="模型预览与版本验收" description="可在左侧切换基础版本和 Blender 精修派生版本。"/><div className="review-layout"><aside className="panel version-panel"><h2>版本历史</h2>{versions.map(v=><button className={active.id===v.id?'active':''} key={v.id} onClick={()=>{setActive(v);setStats({})}}><Box/><span><b>v{String(v.number).padStart(3,'0')}</b><small>{v.label}</small></span>{v===versions[0]&&<em>当前版本</em>}</button>)}<h2>部件树</h2><div className="part-tree"><span>◇ Root</span><span>　◇ {selected}</span><span>　　<Eye/> Mesh</span></div></aside><section className="review-center">{active.model?<ModelViewport url={active.model.url} onStats={setStats} onSelect={setSelected}/>:<div className="viewport-error">当前版本没有可用 GLB 产物</div>}<div className="download-bar"><button onClick={()=>nav(`/plan/${projectId}`)}>↻ 重新生成基线</button><button onClick={()=>nav(`/refinement/new/${active.id}`)}><Wrench/> 创建精修任务</button><button className="accept" disabled={busy||isAccepted} onClick={accept}><CheckCircle2/> {isAccepted?'版本已确认':'确认当前版本'}</button></div></section><aside className="panel acceptance"><h2>版本验收</h2><div className="baseline-evidence"><p><CheckCircle2/> GLB 产物 <b>{active.model?'可用':'缺失'}</b></p><p><CheckCircle2/> 状态 <b>{active.status}</b></p></div><h3>几何统计</h3><dl>{Object.entries({...reportStats,...stats}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='number'?v.toLocaleString():String(v)}</dd></div>)}</dl><h3>已知差异</h3>{differences.length?differences.map((d,i)=><p className="difference" key={i}><span/> {d.message}</p>):<p className="difference">当前报告未记录已知差异。</p>}{error&&<div className="notice danger">{error}</div>}</aside></div></>
}
