import type {Project,Asset,Validation,Job,Version,RefinementJob} from './types';
const json = async <T>(r:Response):Promise<T> => { if(!r.ok){const body=await r.json().catch(()=>({detail:r.statusText}));throw new Error(body.detail||body.error?.message||r.statusText)} return r.json() };
export const api = {
 health:()=>fetch('/api/system/health').then(json),
 projects:(query='')=>fetch(`/api/projects${query}`).then(json<Project[]>),
 project:(id:string)=>fetch(`/api/projects/${id}`).then(json<Project>),
 createProject:(body:unknown)=>fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(json<Project>),
 updateProject:(id:string,body:unknown)=>fetch(`/api/projects/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(json<Project>),
 assets:(id:string)=>fetch(`/api/projects/${id}/assets`).then(json<Asset[]>),
 upload:(id:string,role:string,file:File,onProgress?:(n:number)=>void)=>new Promise<Asset>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',`/api/projects/${id}/assets?role=${encodeURIComponent(role)}`);x.upload.onprogress=e=>e.lengthComputable&&onProgress?.(Math.round(e.loaded/e.total*100));x.onload=()=>x.status<300?resolve(JSON.parse(x.responseText)):reject(new Error(JSON.parse(x.responseText)?.detail||'上传失败'));x.onerror=()=>reject(new Error('网络错误'));const f=new FormData();f.append('file',file);x.send(f)}),
 validate:(id:string)=>fetch(`/api/projects/${id}/validate`,{method:'POST'}).then(json<Validation>),
 validation:(id:string)=>fetch(`/api/projects/${id}/validation`).then(json<Validation>),
 acceptRisks:(id:string)=>fetch(`/api/projects/${id}/validation/accept-risks`,{method:'POST'}).then(json<Validation>),
 plan:(id:string)=>fetch(`/api/projects/${id}/plan`).then(json),
 updatePlan:(id:string,body:unknown)=>fetch(`/api/projects/${id}/plan`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(json),
 createJob:(id:string)=>fetch(`/api/projects/${id}/jobs`,{method:'POST'}).then(json<Job>),
 job:(id:string)=>fetch(`/api/jobs/${id}`).then(json<Job>),
 retry:(id:string)=>fetch(`/api/jobs/${id}/retry`,{method:'POST'}).then(json<Job>),
 cancel:(id:string)=>fetch(`/api/jobs/${id}/cancel`,{method:'POST'}).then(json<Job>),
 versions:(id:string)=>fetch(`/api/projects/${id}/versions`).then(json<Version[]>),
 version:(id:string)=>fetch(`/api/versions/${id}`).then(json<Version>),
 decide:(id:string,decision:string,notes:string)=>fetch(`/api/versions/${id}/${decision}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes})}).then(json),
 revise:(id:string,body:unknown)=>fetch(`/api/versions/${id}/revisions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(json),
 refinementModules:()=>fetch('/api/refinement/modules').then(json<Record<string,{label:string;capability:string;description:string;dependencies?:string[]}>>),
 createRefinement:(body:unknown)=>fetch('/api/refinement/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(json<RefinementJob>),
 refinement:(id:string)=>fetch(`/api/refinement/jobs/${id}`).then(json<RefinementJob>),
 cancelRefinement:(id:string)=>fetch(`/api/refinement/jobs/${id}/cancel`,{method:'POST'}).then(json<RefinementJob>),
 refinements:(id:string)=>fetch(`/api/projects/${id}/refinement-jobs`).then(json<RefinementJob[]>),
};
