export type ProjectStatus = 'draft'|'uploading'|'validating'|'needs_input'|'awaiting_confirmation'|'queued'|'generating_geometry'|'validating_glb'|'rendering_review'|'quality_failed'|'awaiting_manual_refine'|'processing_materials'|'optimizing_web'|'ready_for_review'|'revision_requested'|'completed'|'completed_with_notes'|'failed'|'cancelled';
export interface Project { id:string; slug:string; name:string; subjectType:'character'|'object'|'hybrid'; intendedUse:'web'|'game'|'animation'|'hero-render'; quality:string; status:ProjectStatus; currentJobId?:string; currentStage?:string; passedStages:number; totalStages:number; actualBackend?:string; thumbnailUrl?:string; createdAt:string; updatedAt:string; }
export interface Asset { id:string; role:string; originalName:string; mimeType:string; byteSize:number; width?:number; height?:number; sha256:string; active:boolean; url?:string; }
export interface ValidationCheck { code:string; label:string; status:'pass'|'warning'|'fail'; evidence:string; affectedRegions?:string[]; }
export interface Validation { verdict:'pass'|'conditional'|'request_input'|'reject'; checks:ValidationCheck[]; risks:{code:string;message:string;consequence:string}[]; acceptedAt?:string; }
export interface Stage { id:string; label:string; status:string; startedAt?:string; completedAt?:string; duration?:string; }
export interface Job { id:string; projectId:string; versionId:string; status:string; requestedBackend:string; actualBackend?:string; currentStage?:string; attempt:number; stages:Stage[]; logs:string[]; artifacts:Artifact[]; }
export interface Artifact { id:string; type:string; label:string; url:string; mimeType:string; byteSize:number; sha256:string; metadata:Record<string,unknown>; }
export interface Version { id:string; projectId:string; number:number; label:string; status:string; model?:Artifact; createdAt:string; qualityReport?:QualityReport; }
export interface QualityReport { scores:Record<string,number>; stats:Record<string,number|string>; differences:{severity:string;message:string}[]; approximations:{region:string;confidence:number;note:string}[]; }
export interface RefinementJob {id:string;projectId:string;sourceVersionId:string;outputVersionId?:string;status:string;config:{modules:string[];instructions:string;geometryRepairStrength:string;uvStrategy:string;uvIslandMargin:number;materialTemplate:string;targetTriangleRange:number[];textureResolution:number;maxWebGlbMB:number};moduleStates:Record<string,string>;logs:string[];artifacts:Artifact[];qualityReport?:Record<string,unknown>;blenderVersion?:string;createdAt:string;startedAt?:string;completedAt?:string;errorSummary?:string}
